- name: installing the redis server
  hosts: redis
  become: yes
  tasks:
  - name: Installing the redis repo file
    ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    state: present