- name: install the user component
  hosts: user
  become: yes
  tasks:
  - name: Setup the node environment
    ansible.builtin.shell: "https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Install the Nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: check whether the User exists or not
    ansible.builtin.command: id roboshop
    register: USERID
    ignore_errors: true

  - name: Create the user
    ansible.builtin.user:
      name: roboshop
    when: USERID.rc != 0

  - name: check whether the directory exists or not
    ansible.builtin.stat:
      path: /app
    register: Directory

  - name: printing the directory existence
    ansible.builtin.debug:
      msg: "output is {{Directory}}"

  - name: Create the App directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: Directory.stat.exists == false
  
  - name: Download the User package
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: extract the User package in app directory
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: Install the dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copying the user service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: Reload the service using daemon
    ansible.builtin.systemd:
      daemon_reload: true
  
  - name: copying the mongodb repo file
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing the mongodb client
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed
  
  - name: Loading the schema
    ansible.builtin.shell: "mongo --host mongodb.suhaildevops.online < /app/schema/user.js"

  - name: Enabling and starting the service
    ansible.builtin.service:
      name: user
      state: started
      enable: yes